export default {
  // USER
  LOGIN: "LOGIN",
  LOGIN_ERR: "LOGIN_ERR",
  REGISTER: "REGISTER",
  REGISTER_ERR: "REGISTER_ERR",
  UPDATE: "UPDATE",
  UPDATE_ERR: "UPDATE_ERR",
  DEACTIVATE_ACCOUNT: "DEACTIVATE_ACCOUNT",
  DEACTIVATE_ACCOUNT_ERR: "DEACTIVATE_ACCOUNT_ERR",
  VERIFY_ME: "VERIFY_ME",
  //
  CREATE_TICKET: "CREATE_TICKET",
  UPDATE_TICKET: "UPDATE_TICKET",
  DELETE_TICKET: "DELETE_TICKET",
  CREATE_TICKET_ERR: "CREATE_TICKET_ERR",
  UPDATE_TICKET_ERR: "UPDATE_TICKET_ERR",
  DELETE_TICKET_ERR: "DELETE_TICKET_ERR",

  GET_ALL_TICKETS: "GET_ALL_TICKETS",
  GET_TICKET: "GET_TICKET",

  GET_ALL_CHARGES: "GET_ALL_CHARGES",
  CREATE_CHARGE: "CREATE_CHARGE"
};
